name: flask-test

on:
  push:
    branches:
      - 'main'
      - 'feature/**'

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Actions
        run: echo 'hello, github actions!'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.10'
      - name: Echo Version
        run: python --version
      - name: Setup Flask
        run: python -m pip install --upgrade pip
        run: python -m pip install -r requirements.txt
        run: flask --version
