name: flask-test

on:
  push:
    branches:
      - 'main'
      - 'feature/**'

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Actions
      - run: echo 'hello, github actions!'